import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import NavBar from '@/components/NavBar'
import { NavBarContext } from '@/NavBarContext'

const inter = Inter({ subsets: ['latin'] })

export default function Cart() {
    console.log('cartjsx run')
  return (
    <NavBarContext.Consumer>
        {({cart, total}) => (
            <>
                <Head>
                    <title>YOUR CART</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div>   
                    <h1>CART</h1>
                </div>
                <ul>
                    {cart.map(({name, price}, idx) => (
                        <li key={idx}>{name}, ${price}</li>
                    ))}
                </ul>
                <p>Total: ${total()}</p>
            </>
        )}
    </NavBarContext.Consumer>
  )
}
